### ISSUE TITLE
Pixtypes does not work for multisite wordpress

### ISSUE THREAD

**Issue by scottge** [pixelgrade/pixtypes#22]
I have a multisite wordpress. I installed and activated pixtypes. In the theme, I set up the metaboxes as below. The metaboxes successfully appears on my main site in the multisite., but none of the sub sites shows the metabox.   I verfied that in the subsites, pixtypes_themes_settings is set correctly in the options table.

$pixtypes_conf_settings = array(
            'first_activation' => true,
            'metaboxes'        => array(
                '_job_listing_the_aside' => array(
                    'id'         => 'job_listing_aside',
                    'title'      => esc_html__( 'Gallery Images', 'mvp' ),
                    'pages'      => array( 'job_listing' ), // Post type
                    'context'    => 'side',
                    'priority'   => 'low',
                    'show_names' => true, // Show field names on the left
                    'fields'     => array(
                        array(
                            'name' => esc_html__( 'Gallery Image', 'mvp' ),
                            'id'   => 'main_image',
                            'type' => 'gallery',
                        ),
                    )
                ),

**Comment by andreilupu** [comment]
Hi
I'm not sure I can replicate this issue. Mostly I'm developing in multisite instances and I never encountered this.

Did you activate the plugin over the network? or you just enable it only on the main site?
