### ISSUE TITLE
Non-breaking space added after editing the Text Block

### ISSUE THREAD

**Issue by allexsava** [pixelgrade/pixtypes#29]
Avem un client https://help.pixelgrade.com/helpdesk/tickets/39501, care dupa fiecare editare a unui block de text pe o pagina cu template-ul **Page Builder**, i se adauga <p>&nbsp;</p> dupa fiecare paragraf. Am facut aici si un mic gif prin care replic problema la el pe site — https://cl.ly/0a3e3z1c3J0j

Am incercat sa replic acest scenario cu clona PILE dar nu reusesc.

**Comment by andreilupu** [comment]
cred ca are o versiune de Pile foarte veche.

inchid pana apare din nou
