### ISSUE TITLE
jQuery.fn.load() is deprecated

### ISSUE THREAD

**Issue by alinclamba** [pixelgrade/pixtypes#44]
After installing WordPress 5.5, using [jQuery Migrate Helper](https://wordpress.org/plugins/enable-jquery-migrate-helper/) plugin, I've got this warning:

`wp-content/plugins/pixtypes/features/metaboxes/js/pixgallery.js: jQuery.fn.load() is deprecated
`

Also, it might help to test the plugin with the latest version of WordPress and release an update, with a mention of the compatibility. For now, the plugin isn't tested with the latest 3 major releases of WordPress and it has been updated more than a year ago.

https://wordpress.org/plugins/pixtypes/

**Comment by alinclamba** [comment]
I recently got another message from someone how uses our Rosa Lite theme:

> I was warned by Wordfence that it appeared to be abandoned and that it hadn't been tested with the 3 latest versions of WP (now 4 possibly, as I see they've just updated again). While I understand things like this probably don't need to be updated because they work fine, it doesn't instill trust in users when they receive those types of warnings. Do you think there's a way of fixing that so they show they're compatible?

**Comment by alinclamba** [comment]
Another one:

>  I was in the process of updating some plugins for my site and I noticed that PixCode, Customify, and PixType are old and haven't been tested for the recent WordPress. Will these not being updated cause issues with my site?

I recently spoke with @madalingorbanescu concerning the necessity of maintenance updates for these plugins.

**Comment by madalingorbanescu** [comment]
I have created a [new issue](https://github.com/pixelgrade/pixtypes/issues/45) where I will address compatibility with WordPress 5.7.
